# Generated by Django 5.2.2 on 2026-06-20 15:55

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]

