# Generated by Django 5.2.2 on 2026-05-30 05:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', 2), ('full_rich_text', 3), ('cards', 12), ('slides', 18), ('carousel_celebrity', 20), ('hozirontal_rule', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('streams.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'max_length': 4096, 'required': True}), 8: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page on your website', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL to external website', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 5), ('title', 6), ('text', 7), ('button_page', 8), ('button_url', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 4), ('cards', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': False}), 15: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('image', 5), ('title', 13), ('description', 14), ('page_chooser', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('slides', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('slides', 17), ('title', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[]], {})}, null=True),
        ),
    ]
