# Generated by Django 5.2.2 on 2026-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailpage',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], null=True),
        ),
    ]
