# Generated by Django 5.2.2 on 2026-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productdetailpage_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailpage',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], null=True),
        ),
    ]
