# Generated by Django 5.2.2 on 2026-02-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productdetailpage_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailpage',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], max_length=6, null=True, verbose_name='Gender'),
        ),
    ]
