# Generated by Django 5.2.2 on 2026-03-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategorylistingpage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubcategoryListingPage',
            new_name='ProductSubcategoryListingPage',
        ),
    ]
