# Generated by Django 5.2.2 on 2026-02-11 20:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHoursSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('contact', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='site_settings.contactsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('street', models.CharField(max_length=64, verbose_name='Ulica in mesto')),
                ('maps_url', models.URLField(help_text='Google maps URL', max_length=64)),
                ('contact', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='site_settings.contactsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', models.CharField(max_length=50, null=True, verbose_name='Naziv')),
                ('phone_number', models.CharField(max_length=35, null=True, verbose_name='Telefonska številka')),
                ('contact', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='site_settings.contactsettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtonet', models.URLField(blank=True, help_text='Avtonet URL', max_length=1000, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', max_length=500, null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', max_length=500, null=True)),
                ('youtube', models.URLField(blank=True, help_text='Youtube URL', max_length=500, null=True)),
                ('tiktok', models.URLField(blank=True, help_text='Tiktok URL', max_length=500, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('day', models.IntegerField(choices=[(1, 'Ponedeljek'), (2, 'Torek'), (3, 'Sreda'), (4, 'Četrtek'), (5, 'Petek'), (6, 'Sobota'), (7, 'Nedelja')], null=True)),
                ('is_closed', models.BooleanField(default=False, null=True)),
                ('from_hour', models.TimeField(blank=True, null=True)),
                ('to_hour', models.TimeField(blank=True, null=True)),
                ('from_hour2', models.TimeField(blank=True, null=True)),
                ('to_hour2', models.TimeField(blank=True, null=True)),
                ('opening_hours', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='site_settings.openinghourssettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
