# Generated by Django 5.2.2 on 2026-02-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_alter_workday_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='avtonet',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='X',
            field=models.URLField(blank=True, help_text='X (Twitter) URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='maps_url',
            field=models.URLField(help_text='Google maps URL or similar', max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(max_length=128, verbose_name='Street and City'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=35, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='tiktok',
            field=models.URLField(blank=True, help_text='TikTok URL', max_length=500, null=True),
        ),
    ]
