# Generated by Django 5.2.2 on 2026-02-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_remove_socialmediasettings_avtonet_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSettings',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='OpeningHoursSettings',
            new_name='OpeningHours',
        ),
        migrations.RenameModel(
            old_name='SocialMediaSettings',
            new_name='SocialMedia',
        ),
    ]
