# Generated by Django 5.2.2 on 2026-02-14 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_companyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='legal_entity_type',
            field=models.CharField(max_length=128, verbose_name='Legal Entity Type'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='show_copyright',
            field=models.BooleanField(default=False, verbose_name='Show Copyright in Footer'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='year_established',
            field=models.PositiveSmallIntegerField(max_length=4, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=2022)], verbose_name='Established in year'),
        ),
    ]
