# Generated by Django 5.2.2 on 2026-02-14 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_companyinfo_legal_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='year_established',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(limit_value=2026)], verbose_name='Established in Year'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='unit',
            field=models.CharField(help_text='Currency to use when showing prices (€, EUR, £, ...)', max_length=32, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True, verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='from_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='From Hour'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='from_hour2',
            field=models.TimeField(blank=True, help_text='Set if reopens in the same day', null=True, verbose_name='From Hour 2'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='is_closed',
            field=models.BooleanField(default=False, null=True, verbose_name='Is Closed'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='to_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='To Hour'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='to_hour2',
            field=models.TimeField(blank=True, null=True, verbose_name='To Hour 2'),
        ),
    ]
