# Generated by Django 5.2.2 on 2026-02-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_companyinfo_year_established_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='maps_url',
            field=models.URLField(help_text='Google maps URL or similar', max_length=64, verbose_name='Location URL'),
        ),
    ]
