# Generated by Django 5.2.2 on 2026-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_alter_location_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='maps_url',
            field=models.URLField(help_text='Google maps URL or similar', max_length=1024, verbose_name='Location URL'),
        ),
    ]
